/**
 * Git Hook 自动安装工具
 * 一键配置 pre-commit / pre-push hook，在提交前自动运行增量扫描
 */

import { existsSync, writeFileSync, readFileSync, chmodSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { execSync } from "node:child_process";
import pc from "picocolors";

export interface HookConfig {
    /** 要安装的 hook 类型 */
    type: "pre-commit" | "pre-push" | "both";
    /** 扫描命令参数 */
    scanArgs?: string;
    /** 是否自动修复 */
    autoFix?: boolean;
    /** 是否启用缓存 */
    cache?: boolean;
    /** 最低 severity 级别 */
    minSeverity?: string;
}

const HOOK_TEMPLATE = `#!/bin/sh
# Auto-generated by frontend-guardian
# 提交前自动运行代码治理扫描

echo "🔍 Frontend Guardian: 正在检查提交文件..."

# 仅扫描 staged 文件
npx fg-core . --scan --staged{{ARGS}}

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ 检查未通过，请修复问题后再提交"
    echo "   使用 --no-verify 跳过检查（不推荐）"
    exit 1
fi

echo "✅ 检查通过"
`;

/**
 * 安装 Git Hook
 * @param projectDir 项目根目录
 * @param config Hook 配置
 * @returns 安装结果
 */
export function installGitHooks(projectDir: string, config: HookConfig): { installed: string[]; skipped: string[] } {
    const installed: string[] = [];
    const skipped: string[] = [];

    // 查找 git 根目录
    let gitDir: string;
    try {
        const gitRoot = execSync("git rev-parse --git-dir", {
            cwd: projectDir,
            encoding: "utf-8",
            stdio: ["pipe", "pipe", "ignore"],
        }).trim();
        gitDir = resolve(projectDir, gitRoot);
    } catch {
        console.log(pc.yellow("⚠️  未找到 Git 仓库，跳过 Hook 安装"));
        return { installed, skipped };
    }

    const hooksDir = resolve(gitDir, "hooks");
    if (!existsSync(hooksDir)) {
        mkdirSync(hooksDir, { recursive: true });
    }

    const types = config.type === "both" ? ["pre-commit", "pre-push"] : [config.type];

    // 构建参数
    const args: string[] = [];
    if (config.autoFix) args.push(" --fix");
    if (config.cache === false) args.push(" --no-cache");
    if (config.minSeverity) args.push(` --severity ${config.minSeverity}`);
    const argsStr = args.join("");

    for (const hookType of types) {
        const hookPath = resolve(hooksDir, hookType);

        // 检查是否已有 hook
        if (existsSync(hookPath)) {
            const existing = readFileSync(hookPath, "utf-8");
            if (existing.includes("frontend-guardian")) {
                // 已安装过，更新内容
                const newContent = HOOK_TEMPLATE.replace("{{ARGS}}", argsStr);
                writeFileSync(hookPath, newContent, "utf-8");
                chmodSync(hookPath, 0o755);
                installed.push(`${hookType} (更新)`);
                continue;
            }

            // 已有其他 hook，询问是否合并（此处静默跳过，实际使用时应提示用户）
            skipped.push(`${hookType} (已有其他 hook)`);
            continue;
        }

        // 新建 hook
        const content = HOOK_TEMPLATE.replace("{{ARGS}}", argsStr);
        writeFileSync(hookPath, content, "utf-8");
        chmodSync(hookPath, 0o755);
        installed.push(hookType);
    }

    return { installed, skipped };
}

/**
 * 卸载 Git Hook
 * @param projectDir 项目根目录
 * @param type 要卸载的 hook 类型
 * @returns 卸载结果
 */
export function uninstallGitHooks(projectDir: string, type: "pre-commit" | "pre-push" | "both"): { removed: string[]; notFound: string[] } {
    const removed: string[] = [];
    const notFound: string[] = [];

    let gitDir: string;
    try {
        const gitRoot = execSync("git rev-parse --git-dir", {
            cwd: projectDir,
            encoding: "utf-8",
            stdio: ["pipe", "pipe", "ignore"],
        }).trim();
        gitDir = resolve(projectDir, gitRoot);
    } catch {
        return { removed, notFound };
    }

    const hooksDir = resolve(gitDir, "hooks");
    const types = type === "both" ? ["pre-commit", "pre-push"] : [type];

    for (const hookType of types) {
        const hookPath = resolve(hooksDir, hookType);
        if (existsSync(hookPath)) {
            const content = readFileSync(hookPath, "utf-8");
            if (content.includes("frontend-guardian")) {
                const fs = require("node:fs");
                fs.unlinkSync(hookPath);
                removed.push(hookType);
            } else {
                notFound.push(`${hookType} (非 fg 生成)`);
            }
        } else {
            notFound.push(hookType);
        }
    }

    return { removed, notFound };
}

/**
 * 检查是否已安装 fg hook
 */
export function hasGitHook(projectDir: string, type: "pre-commit" | "pre-push"): boolean {
    try {
        const gitRoot = execSync("git rev-parse --git-dir", {
            cwd: projectDir,
            encoding: "utf-8",
            stdio: "pipe",
        }).trim();
        const hookPath = resolve(projectDir, gitRoot, "hooks", type);
        if (!existsSync(hookPath)) return false;
        const content = readFileSync(hookPath, "utf-8");
        return content.includes("frontend-guardian");
    } catch {
        return false;
    }
}
