/**
 * Git Hook 自动安装工具
 * 一键配置 pre-commit / pre-push hook，在提交前自动运行增量扫描
 */

import { existsSync, writeFileSync, readFileSync, chmodSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { execSync } from "node:child_process";
import pc from "picocolors";

export interface HookConfig {
    /** 要安装的 hook 类型 */
    type: "pre-commit" | "pre-push" | "commit-msg" | "both" | "all";
    /** 扫描命令参数 */
    scanArgs?: string;
    /** 是否自动修复 */
    autoFix?: boolean;
    /** 是否启用缓存 */
    cache?: boolean;
    /** 最低 severity 级别 */
    minSeverity?: string;
    /** commit-msg 自定义正则（默认 Conventional Commits） */
    commitMsgPattern?: string;
    /** 是否允许空提交消息 */
    allowEmpty?: boolean;
}

const HOOK_TEMPLATE_PRE_COMMIT = `#!/bin/sh
# Auto-generated by frontend-guardian
# 提交前自动运行增量扫描（仅 staged 文件）

echo "🔍 Frontend Guardian: 正在检查提交文件..."

npx fg-core . --scan --staged{{ARGS}}

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ 检查未通过，请修复问题后再提交"
    echo "   使用 --no-verify 跳过检查（不推荐）"
    exit 1
fi

echo "✅ 检查通过"
`;

const HOOK_TEMPLATE_PRE_PUSH = `#!/bin/sh
# Auto-generated by frontend-guardian
# 推送前自动运行全量扫描

echo "🔍 Frontend Guardian: 正在运行全量扫描..."

npx fg-core . --scan{{ARGS}}

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ 检查未通过，请修复问题后再推送"
    echo "   使用 --no-verify 跳过检查（不推荐）"
    exit 1
fi

echo "✅ 检查通过"
`;

const HOOK_TEMPLATE_COMMIT_MSG = `#!/bin/sh
# Auto-generated by frontend-guardian
# 检查 commit message 是否符合 Conventional Commits 规范

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# 跳过 merge commit、revert、amend
if echo "$COMMIT_MSG" | grep -qE "^Merge |^Revert |^fixup! |^squash! "; then
    exit 0
fi

# 跳过空消息检查（如果配置允许）
{{ALLOW_EMPTY}}

# Conventional Commits 正则
PATTERN="{{PATTERN}}"

if ! echo "$COMMIT_MSG" | grep -qE "$PATTERN"; then
    echo "❌ Commit message 格式不符合规范"
    echo ""
    echo "   期望格式: <type>[(scope)]: <subject>"
    echo ""
    echo "   支持的 type:"
    echo "     feat     新功能"
    echo "     fix      修复"
    echo "     docs     文档"
    echo "     style    代码格式"
    echo "     refactor 重构"
    echo "     perf     性能优化"
    echo "     test     测试"
    echo "     build    构建"
    echo "     ci       CI/CD"
    echo "     chore    杂项"
    echo "     revert   回滚"
    echo ""
    echo "   示例:"
    echo "     feat(auth): 添加登录页面"
    echo "     fix: 修复空指针异常"
    echo ""
    echo "   当前消息:"
    echo "     $COMMIT_MSG"
    exit 1
fi

echo "✅ Commit message 格式检查通过"
`;

/**
 * 检测项目是否使用 husky
 * @param projectDir 项目根目录
 * @returns husky 配置信息
 */
export function detectHusky(projectDir: string): { useHusky: boolean; huskyDir: string | null; version: "v8+" | "legacy" | null } {
    const huskyDirV8 = resolve(projectDir, ".husky");
    const huskyDirLegacy = resolve(projectDir, ".husky/_/husky.sh");

    if (existsSync(huskyDirV8)) {
        return { useHusky: true, huskyDir: huskyDirV8, version: "v8+" };
    }

    if (existsSync(huskyDirLegacy)) {
        return { useHusky: true, huskyDir: huskyDirV8, version: "legacy" };
    }

    return { useHusky: false, huskyDir: null, version: null };
}

/**
 * 安装 Git Hook
 * @param projectDir 项目根目录
 * @param config Hook 配置
 * @returns 安装结果
 */
export function installGitHooks(projectDir: string, config: HookConfig): { installed: string[]; skipped: string[] } {
    const installed: string[] = [];
    const skipped: string[] = [];

    // 查找 git 根目录
    let gitDir: string;
    try {
        const gitRoot = execSync("git rev-parse --git-dir", {
            cwd: projectDir,
            encoding: "utf-8",
            stdio: ["pipe", "pipe", "ignore"],
        }).trim();
        gitDir = resolve(projectDir, gitRoot);
    } catch {
        console.log(pc.yellow("⚠️  未找到 Git 仓库，跳过 Hook 安装"));
        return { installed, skipped };
    }

    // 检测 husky
    const huskyInfo = detectHusky(projectDir);
    const useHusky = huskyInfo.useHusky;
    const hooksDir = useHusky && huskyInfo.huskyDir
        ? huskyInfo.huskyDir
        : resolve(gitDir, "hooks");

    if (!existsSync(hooksDir)) {
        mkdirSync(hooksDir, { recursive: true });
    }

    const types: string[] = (() => {
        switch (config.type) {
            case "both": return ["pre-commit", "pre-push"];
            case "all": return ["pre-commit", "pre-push", "commit-msg"];
            default: return [config.type];
        }
    })();

    // 构建参数
    const args: string[] = [];
    if (config.autoFix) args.push(" --fix");
    if (config.cache === false) args.push(" --no-cache");
    if (config.minSeverity) args.push(` --severity ${config.minSeverity}`);
    const argsStr = args.join("");

    for (const hookType of types) {
        const hookPath = resolve(hooksDir, hookType);
        let template: string;
        if (hookType === "pre-push") {
            template = HOOK_TEMPLATE_PRE_PUSH;
        } else if (hookType === "commit-msg") {
            template = HOOK_TEMPLATE_COMMIT_MSG;
        } else {
            template = HOOK_TEMPLATE_PRE_COMMIT;
        }

        // 检查是否已有 hook
        if (existsSync(hookPath)) {
            const existing = readFileSync(hookPath, "utf-8");
            if (existing.includes("frontend-guardian")) {
                // 已安装过，更新内容
                const newContent = buildHookContent(template, argsStr, hookType, config, useHusky);
                writeFileSync(hookPath, newContent, "utf-8");
                if (!useHusky) chmodSync(hookPath, 0o755);
                installed.push(`${hookType}${useHusky ? " (husky)" : ""} (更新)`);
                continue;
            }

            // 已有其他 hook，询问是否合并（此处静默跳过，实际使用时应提示用户）
            skipped.push(`${hookType}${useHusky ? " (husky)" : ""} (已有其他 hook)`);
            continue;
        }

        // 新建 hook
        const content = buildHookContent(template, argsStr, hookType, config, useHusky);
        writeFileSync(hookPath, content, "utf-8");
        if (!useHusky) chmodSync(hookPath, 0o755);
        installed.push(`${hookType}${useHusky ? " (husky)" : ""}`);
    }

    return { installed, skipped };
}

/**
 * 构建 hook 内容，根据类型应用不同替换
 */
function buildHookContent(
    template: string,
    argsStr: string,
    hookType: string,
    config: HookConfig,
    useHusky: boolean
): string {
    let content = template;
    if (hookType === "commit-msg") {
        // Conventional Commits 默认正则
        const pattern = config.commitMsgPattern ||
            "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\(.+\\))?!?: .+";
        const allowEmpty = config.allowEmpty
            ? "# 允许空消息\nif [ -z \"$COMMIT_MSG\" ] || [ \"$COMMIT_MSG\" = \"\" ]; then\n    exit 0\nfi\n"
            : "# 空消息检查（默认拒绝）\nif [ -z \"$COMMIT_MSG\" ] || [ \"$COMMIT_MSG\" = \"\" ]; then\n    echo \"❌ Commit message 不能为空\"\n    exit 1\nfi\n";
        content = content.replace("{{PATTERN}}", pattern);
        content = content.replace("{{ALLOW_EMPTY}}", allowEmpty);
    } else {
        content = content.replace("{{ARGS}}", argsStr);
    }
    if (useHusky) {
        content = toHuskyScript(content, argsStr);
    }
    return content;
}

/**
 * 将 shell hook 模板转换为 husky v8+ 脚本格式
 */
function toHuskyScript(template: string, argsStr: string): string {
    // 移除 shebang，husky v8+ 不需要
    const lines = template
        .replace("#!/bin/sh\n", "")
        .split("\n")
        .filter((line) => !line.startsWith("# ") || line.includes("frontend-guardian"));

    // 替换命令中的 {{ARGS}}
    return lines
        .join("\n")
        .replace("{{ARGS}}", argsStr)
        .trim();
}

/**
 * 卸载 Git Hook
 * @param projectDir 项目根目录
 * @param type 要卸载的 hook 类型
 * @returns 卸载结果
 */
export function uninstallGitHooks(projectDir: string, type: "pre-commit" | "pre-push" | "commit-msg" | "both" | "all"): { removed: string[]; notFound: string[] } {
    const removed: string[] = [];
    const notFound: string[] = [];

    let gitDir: string;
    try {
        const gitRoot = execSync("git rev-parse --git-dir", {
            cwd: projectDir,
            encoding: "utf-8",
            stdio: ["pipe", "pipe", "ignore"],
        }).trim();
        gitDir = resolve(projectDir, gitRoot);
    } catch {
        return { removed, notFound };
    }

    const huskyInfo = detectHusky(projectDir);
    const hooksDir = huskyInfo.useHusky && huskyInfo.huskyDir
        ? huskyInfo.huskyDir
        : resolve(gitDir, "hooks");

    const types: string[] = (() => {
        switch (type) {
            case "both": return ["pre-commit", "pre-push"];
            case "all": return ["pre-commit", "pre-push", "commit-msg"];
            default: return [type];
        }
    })();

    for (const hookType of types) {
        const hookPath = resolve(hooksDir, hookType);
        if (existsSync(hookPath)) {
            const content = readFileSync(hookPath, "utf-8");
            if (content.includes("frontend-guardian")) {
                const fs = require("node:fs");
                fs.unlinkSync(hookPath);
                removed.push(`${hookType}${huskyInfo.useHusky ? " (husky)" : ""}`);
            } else {
                notFound.push(`${hookType}${huskyInfo.useHusky ? " (husky)" : ""} (非 fg 生成)`);
            }
        } else {
            notFound.push(hookType);
        }
    }

    return { removed, notFound };
}

/**
 * 检查是否已安装 fg hook
 */
export function hasGitHook(projectDir: string, type: "pre-commit" | "pre-push" | "commit-msg"): boolean {
    try {
        const huskyInfo = detectHusky(projectDir);
        if (huskyInfo.useHusky && huskyInfo.huskyDir) {
            const hookPath = resolve(huskyInfo.huskyDir, type);
            if (existsSync(hookPath)) {
                const content = readFileSync(hookPath, "utf-8");
                return content.includes("frontend-guardian");
            }
            return false;
        }

        const gitRoot = execSync("git rev-parse --git-dir", {
            cwd: projectDir,
            encoding: "utf-8",
            stdio: "pipe",
        }).trim();
        const hookPath = resolve(projectDir, gitRoot, "hooks", type);
        if (!existsSync(hookPath)) return false;
        const content = readFileSync(hookPath, "utf-8");
        return content.includes("frontend-guardian");
    } catch {
        return false;
    }
}
