#!/usr/bin/env bash
#
# export-report.sh — 报告导出（Markdown → HTML）
# Usage: export-report.sh <input.md> [output.html]

set -euo pipefail

INPUT="${1:-./frontend-guardian-report.md}"
OUTPUT="${2:-${INPUT%.md}.html}"

if [[ ! -f "$INPUT" ]]; then
  echo "❌ 输入文件不存在: $INPUT"
  exit 1
fi

# 简单的 Markdown 转 HTML
markdown_to_html() {
  local md="$1"
  local html=""

  html="<!DOCTYPE html>
<html lang=\"zh-CN\">
<head>
<meta charset=\"UTF-8\">
<title>Frontend Guardian 扫描报告</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px 20px; color: #333; line-height: 1.6; }
h1 { color: #1890ff; border-bottom: 2px solid #1890ff; padding-bottom: 10px; }
h2 { color: #333; border-bottom: 1px solid #eee; padding-bottom: 8px; margin-top: 30px; }
h3 { color: #555; }
table { border-collapse: collapse; width: 100%; margin: 16px 0; }
th, td { border: 1px solid #ddd; padding: 10px 14px; text-align: left; }
th { background: #f5f5f5; font-weight: 600; }
tr:nth-child(even) { background: #fafafa; }
code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
pre { background: #f8f8f8; padding: 16px; border-radius: 6px; overflow-x: auto; }
pre code { background: none; padding: 0; }
.critical { color: #ff4d4f; }
.warning { color: #faad14; }
.suggestion { color: #1890ff; }
.summary { background: #f0f5ff; padding: 16px; border-radius: 8px; margin: 16px 0; }
.footer { text-align: center; color: #999; margin-top: 40px; font-size: 0.85em; }
</style>
</head>
<body>"

  # 逐行转换
  local in_code=false
  while IFS= read -r line; do
    # 代码块
    if [[ "$line" =~ ^'\`\`\`' ]]; then
      if $in_code; then
        html+="\n</pre>"
        in_code=false
      else
        html+="\n<pre><code>"
        in_code=true
      fi
      continue
    fi

    if $in_code; then
      html+="\n$(echo "$line" | sed 's/&/&amp;/g; s/</&lt;/g; s/>/&gt;/g')"
      continue
    fi

    # 标题
    if [[ "$line" =~ ^######\s+(.*)$ ]]; then
      html+="\n<h6>${BASH_REMATCH[1]}</h6>"
    elif [[ "$line" =~ ^#####\s+(.*)$ ]]; then
      html+="\n<h5>${BASH_REMATCH[1]}</h5>"
    elif [[ "$line" =~ ^####\s+(.*)$ ]]; then
      html+="\n<h4>${BASH_REMATCH[1]}</h4>"
    elif [[ "$line" =~ ^###\s+(.*)$ ]]; then
      html+="\n<h3>${BASH_REMATCH[1]}</h3>"
    elif [[ "$line" =~ ^##\s+(.*)$ ]]; then
      html+="\n<h2>${BASH_REMATCH[1]}</h2>"
    elif [[ "$line" =~ ^#\s+(.*)$ ]]; then
      html+="\n<h1>${BASH_REMATCH[1]}</h1>"
    # 表格
    elif [[ "$line" =~ ^\|.*\|$ ]]; then
      # 跳过分隔行
      if [[ "$line" =~ ^\|[\s\-:]+\|$ ]]; then
        continue
      fi
      html+="\n<tr>"
      local cells=$(echo "$line" | tr '|' '\n' | tail -n +2 | head -n -1)
      while IFS= read -r cell; do
        local trimmed=$(echo "$cell" | sed 's/^ *//;s/ *$//')
        html+="<td>$trimmed</td>"
      done <<< "$cells"
      html+="</tr>"
    # 列表
    elif [[ "$line" =~ ^\*\s+(.*)$ ]]; then
      html+="\n<li>${BASH_REMATCH[1]}</li>"
    elif [[ "$line" =~ ^-\s+(.*)$ ]]; then
      html+="\n<li>${BASH_REMATCH[1]}</li>"
    # 空行
    elif [[ -z "$line" ]]; then
      html+="\n<p></p>"
    # 普通段落
    else
      local p=$(echo "$line" | sed 's/\*\*\([^*]*\)\*\*/<strong>\1<\/strong>/g; s/\*\([^*]*\)\*/<em>\1<\/em>/g; s/`\([^`]*\)`/<code>\1<\/code>/g')
      html+="\n<p>$p</p>"
    fi
  done < "$md"

  html+="\n<div class=\"footer\">Generated by Frontend Guardian</div>"
  html+="\n</body>\n</html>"

  echo "$html"
}

echo "📄 导出报告: $INPUT → $OUTPUT"
markdown_to_html "$INPUT" > "$OUTPUT"
echo "✅ 导出完成: $OUTPUT"
